# Generated by Django 3.1.2 on 2020-11-13 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetName', models.CharField(max_length=100)),
                ('SerialNum', models.CharField(blank=True, max_length=100, null=True)),
                ('AssetNum', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(max_length=100)),
                ('Office', models.CharField(max_length=100)),
                ('IssuedTo', models.CharField(max_length=100)),
                ('DatePurch', models.DateField(default=django.utils.timezone.now)),
                ('DisposalDate', models.DateField()),
            ],
        ),
    ]
