# Generated by Django 3.1.2 on 2020-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0002_asset_regionaloffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Status',
            field=models.CharField(choices=[('WORKING', 'working'), ('NOT FUNCTIONAL', 'not functional')], default='working', max_length=15),
        ),
    ]
