# Generated by Django 3.1.2 on 2020-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0003_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='RegionalOffice',
            field=models.CharField(choices=[('HARARE', 'Harare'), ('RUSAPE', 'Rusape'), ('CHINHOI', 'Chinhoi'), ('MVURWI', 'Mvurwi'), ('BINDURA', 'Bindura'), ('KAROI', 'Karoi'), ('MUTARE', 'Mutare'), ('MARONDERA', 'Marondera')], default='Harare', max_length=15),
        ),
    ]
