# Generated by Django 3.1.2 on 2020-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0004_auto_20201203_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Status',
            field=models.CharField(choices=[('WORKING', 'Working'), ('NOT FUNCTIONAL', 'Not functional')], default='working', max_length=15),
        ),
    ]
