# Generated by Django 3.1.2 on 2021-05-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0007_auto_20210511_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
    ]
