# Generated by Django 3.1.2 on 2021-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0008_remove_asset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AssetName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='IssuedTo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Office',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
