# Generated by Django 3.1.2 on 2021-05-12 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0009_auto_20210512_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AssetName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='DatePurch',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='DisposalDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='IssuedTo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='RegionalOffice',
            field=models.CharField(blank=True, choices=[('HARARE', 'Harare'), ('RUSAPE', 'Rusape'), ('CHINHOI', 'Chinhoi'), ('MVURWI', 'Mvurwi'), ('BINDURA', 'Bindura'), ('KAROI', 'Karoi'), ('MUTARE', 'Mutare'), ('MARONDERA', 'Marondera')], default='Harare', max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Status',
            field=models.CharField(blank=True, choices=[('WORKING', 'Working'), ('NOT FUNCTIONAL', 'Not functional')], default='working', max_length=15),
        ),
    ]
