# Generated by Django 3.1.2 on 2021-05-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0013_auto_20210513_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='export_to_PDF',
            field=models.BooleanField(default=False),
        ),
    ]
