# Generated by Django 3.1.2 on 2021-05-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asm', '0014_auto_20210513_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='export_to_CSV',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='export_to_PDF',
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='RegionalOffice',
            field=models.CharField(blank=True, choices=[('HARARE', 'Harare'), ('RUSAPE', 'Rusape'), ('CHINHOI', 'Chinhoi'), ('MVURWI', 'Mvurwi'), ('BINDURA', 'Bindura')], default='Harare', max_length=15),
        ),
    ]
