# Generated by Django 3.1.2 on 2021-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0015_auto_20210513_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='RegionalOffice',
            field=models.CharField(blank=True, choices=[('HARARE', 'Harare'), ('RUSAPE', 'Rusape'), ('CHINHOI', 'Chinhoi'), ('MVURWI', 'Mvurwi'), ('BINDURA', 'Bindura'), ('MUTARE', 'Mutare')], default='Harare', max_length=15),
        ),
    ]
