# Generated by Django 3.1.2 on 2021-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0018_auto_20210514_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='export_to_PDF',
            field=models.BooleanField(default=False),
        ),
    ]
