# Generated by Django 3.1.2 on 2021-05-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asm', '0019_auto_20210514_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='export_to_CSV',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='export_to_PDF',
        ),
    ]
